# Generated by Django 2.0.7 on 2018-07-13 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('writingwiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelAns',
            fields=[
                ('ansid', models.IntegerField(db_column='ansID', primary_key=True, serialize=False)),
                ('ans', models.TextField()),
            ],
            options={
                'db_table': 'model_ans',
            },
        ),
        migrations.CreateModel(
            name='Pictorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picid', models.IntegerField(db_column='picID')),
                ('url', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'pictorial',
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('questionid', models.IntegerField(db_column='questionID', primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('questionCategory', models.CharField(db_column='questionCategory', max_length=255)),
                ('questionType', models.CharField(db_column='questionType', max_length=255)),
            ],
            options={
                'db_table': 'questions',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmation_code', models.CharField(max_length=1000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='greeting',
            name='when',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date created'),
        ),
        migrations.AddField(
            model_name='pictorial',
            name='questionid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='writingwiz.Questions'),
        ),
        migrations.AddField(
            model_name='modelans',
            name='questionid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='writingwiz.Questions'),
        ),
    ]
