# Generated by Django 4.2.30 on 2026-09-22 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writingwiz', '0002_auto_20180713_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('noOfViews', models.IntegerField(blank=True, db_column='noOfViews', default=0, null=True)),
                ('dateCreated', models.DateTimeField(blank=True, db_column='dateCreated', null=True)),
            ],
            options={
                'db_table': 'learningvideos',
            },
        ),
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('phrase', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=255)),
                ('theme', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'phrases',
            },
        ),
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('vocabulary', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=255)),
                ('theme', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'vocabularies',
            },
        ),
        migrations.CreateModel(
            name='VpCategory',
            fields=[
                ('category', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'vpcat',
            },
        ),
    ]
