# Generated by Django 4.2.30 on 2026-09-25 16:22

from django.db import migrations, models
import writingwiz.models


class Migration(migrations.Migration):

    dependencies = [
        ('writingwiz', '0003_learningvideo_phrase_vocabulary_vpcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vocabulary',
            options={'verbose_name_plural': 'Vocabularies'},
        ),
        migrations.AlterModelOptions(
            name='vpcategory',
            options={'verbose_name_plural': 'VP categories'},
        ),
        migrations.AlterField(
            model_name='learningvideo',
            name='dateCreated',
            field=models.DateTimeField(auto_now_add=True, db_column='dateCreated', null=True),
        ),
        migrations.AlterField(
            model_name='modelans',
            name='ansid',
            field=models.IntegerField(db_column='ansID', default=writingwiz.models._next_ans_id, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pictorial',
            name='picid',
            field=models.IntegerField(db_column='picID', default=writingwiz.models._next_pic_id),
        ),
        migrations.AlterField(
            model_name='questions',
            name='questionid',
            field=models.IntegerField(db_column='questionID', default=writingwiz.models._next_question_id, primary_key=True, serialize=False),
        ),
    ]
