# Generated by Django 4.2.30 on 2026-09-27 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writingwiz', '0004_alter_vocabulary_options_alter_vpcategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='theme',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
