# Generated by Django 4.2.30 on 2026-09-28 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('writingwiz', '0005_questions_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='EssayAttempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtype', models.CharField(max_length=20)),
                ('essay_text', models.TextField()),
                ('total_score', models.FloatField()),
                ('total_max', models.FloatField()),
                ('content_score', models.FloatField()),
                ('language_score', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='essay_attempts', to='writingwiz.questions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='essay_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'essay_attempts',
                'ordering': ['-created_at'],
            },
        ),
    ]
