# Generated by Django 4.2.30 on 2026-09-29 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writingwiz', '0007_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='essayattempt',
            name='breakdown',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='essayattempt',
            name='content_max',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='essayattempt',
            name='language_max',
            field=models.FloatField(default=0),
        ),
    ]
