# Generated by Django 4.2.30 on 2026-10-01 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writingwiz', '0008_essayattempt_breakdown_essayattempt_content_max_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_enabled', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'site_settings',
            },
        ),
    ]
