# Generated by Django 4.2.30 on 2026-10-01 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writingwiz', '0009_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='google_signin_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
