# Generated by Django 4.2.30 on 2026-10-01 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writingwiz', '0010_sitesettings_google_signin_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='essayattempt',
            name='suggestions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
