# Generated by Django 4.2.30 on 2026-10-02 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('writingwiz', '0011_essayattempt_suggestions'),
    ]

    operations = [
        migrations.CreateModel(
            name='VividVocabularyUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('vocabulary', 'Vocabulary'), ('phrase', 'Phrase')], max_length=20)),
                ('text', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vivid_vocabulary_usages', to='writingwiz.essayattempt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vivid_vocabulary_usages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vivid_vocabulary_usages',
            },
        ),
    ]
